위치 관련 기능 클래스 생성 및 구글 맵 API키 변경
CPstudy/GogumaProject pull request #10
Opened 2021-01-31 11:32 UTC by CPstudy

* LocationHelper 클래스를 만들어 위치 권한, 위치 정보 취득 부분을 분리함

2021-02-01 03:49 UTC, Zimins requested changes
고생했어~ 액티비티의 과도한 로직을 이동시키는 의도가 좋은거 같아.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +}
아이디어는 좋은데, Kotlin 에서는 helper 클래스보다는 가능하면 파일단위 함수를 지향하기는해.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +class LocationHelper(private val activity: Activity) {
이 클래스를 쓰는 쪽을 보면 `LocationHelper(this).xxx` 이렇게 사용되는데, 액티비티에 대한 참조가 생성자로 있을 필요가 있을까? 메소드에 파라미터로 줘도 가능할거같은데 어떻게 생각해?

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +    private lateinit var callback: (LatLng) -> Unit
latent 필드에 대한 초기화가 꼭 나중에 되어야 한다면, 별도 팩토리 메소드 구현이 잇는게 좋은거같아. 
이 필드들이 초기화 되지 않았으면 메소드 호출순서가 달라지면  크래시가 날 수도 있고, 생성하는 코드가 한곳에 있는게 보기도 좋고.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +    fun location(callback: (LatLng) -> (Unit)) {
그냥 `location` 이라고만 하면 무슨 역할을 하는 함수인지 알기가 어려우니까, 동사의 의미가 있는`locate` 나 `getCurrentLocation` 처럼 정확한 이름이 좋을거같아. 파라미터도 그냥 callback 보다는 `onLocationLoad`, `onSuccess`, 등 있지.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +    fun location(callback: (LatLng) -> (Unit)) {
이 메소드에서는 callback 파라미터를 필드에 할당하기만 하는데, 일반적으로는 callback만 설정하는 setter를 두거나 메소드를 주는게 좋을거같아.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +            fastestInterval = 5000
일단 이 숫자들은 상수가 더 좋을거같아.

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +        }
builder을 쓰는쪽을 보니 build() 만 사용하는데 그러면 이 변수를 builder로 두기 보다는 build() 결과로 두면 어떨까? 그리고 let을 쓴 이유가 어떤거야?

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +        val task: Task<LocationSettingsResponse> = client.checkLocationSettings(builder?.build())
builder가 ? 아니어도 될거같은데 맞아?

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +            Toast.makeText(activity.applicationContext, "권한이 없습니다. 안타깝습니다.", Toast.LENGTH_LONG).show()
메시지를 좀 더 착하게 하자 우리 ㅋㅋㅋ

2021-02-01 03:49 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/MainActivity.kt
> +            }
최종적으로 여기는 예를들면 이런 형태가 어떨까?
```suggestion
            requestDeviceLocation(activity, onSuccess = {
                 // moveCamera
            })
```

2021-02-01 13:46 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +}
`파일단위 함수`가 무엇을 의미하는 바인가?

2021-02-01 13:47 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +class LocationHelper(private val activity: Activity) {
파라미터로 넘기는 것이 좋을 것 같다고 생각하는 부분에 동감함

2021-02-01 13:48 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +    fun location(callback: (LatLng) -> (Unit)) {
접수

2021-02-01 13:48 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +            fastestInterval = 5000
접수

2021-02-01 13:52 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/MainActivity.kt
> +            }
어떻게 이렇게 되는건가?

2021-02-02 01:47 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +}
클래스 없이 파일에다가 함수 정의하는거

2021-02-02 01:48 UTC, Zimins commented on app/src/main/java/com/cpstudy/gogumaproject/MainActivity.kt
> +            }
위 리뷰들을 반영해서 이런 형태의 메소드면 좋을거 같다는 뜻이야

2021-02-04 14:08 UTC, CPstudy commented on app/src/main/java/com/cpstudy/gogumaproject/LocationHelper.kt
> +}
위치 정보를 얻기 위해 checkPermission 함수도 매번 필요한데 클래스로 묶어놓는게 편하지 않나?

2021-02-09 09:56 UTC, Zimins commented
conflict 수정해줘~

2021-02-09 14:58 UTC, merged